=== CharlesAttend/M1-S1-DAC/MLBDA/TME/TME6/Exercice1/Question2/base-contrainte.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- <!DOCTYPE xs:schema SYSTEM "XMLSchema.dtd"> -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="base">
    <xs:complexType>
        <xs:choice minOccurs="0" maxOccurs="unbounded">

            <xs:element name="restaurant" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <!-- Type fermeture simple -->
                        <xs:element name="fermeture" minOccurs="0"></xs:element>
                        
                        <!-- Type Menu avec attribute-->
                        <xs:element name="menu" minOccurs="2" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:attribute name="nom" type="xs:string"></xs:attribute>
                                <xs:attribute name="prix" type="xs:integer"></xs:attribute>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>

                    <!-- Attribus de Restaurant -->
                    <xs:attribute name="nom" type="xs:string"></xs:attribute>
                    <xs:attribute name="etoile">
                        <xs:simpleType>
                            <xs:restriction base="xs:integer">
                                <xs:minInclusive value="0"></xs:minInclusive>
                                <xs:maxInclusive value="3"></xs:maxInclusive>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="ville" type="xs:string"></xs:attribute>
                    
                </xs:complexType>

                
            </xs:element>

            <xs:element name="ville" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>

                        <xs:element name="plusBeauMonument" minOccurs="0" maxOccurs="1">
                            <xs:complexType>
                                <xs:attribute name="nom" type="xs:string" use="required"></xs:attribute>
                                <xs:attribute name="tarif" type="xs:integer" use="required"></xs:attribute>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>

                    <!-- Attribus de Ville -->
                    <xs:attribute name="nom" type="xs:string" use="required"></xs:attribute>
                    <xs:attribute name="departement" type="xs:integer" use="required"></xs:attribute>
                </xs:complexType>
                
            </xs:element>
            
        </xs:choice>
    </xs:complexType>
    
    <!-- Ville : Key -->
    <xs:key name="idVille">
        <xs:selector xpath="ville"></xs:selector>
        <xs:field xpath="@nom"></xs:field>
    </xs:key>
    
    <!-- Restaurant Ref ville -->
    <xs:keyref refer="idVille" name="refVille">
        <xs:selector xpath="restaurant"></xs:selector>
        <xs:field xpath="@ville"></xs:field>
    </xs:keyref>

</xs:element>

</xs:schema>

=== CharlesAttend/M1-S1-DAC/MLBDA/TME/TME6/Exercice1/Question2/base-sans-contrainte.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
   Ce document n'est pas valide par rapport a base-contrainte.xsd
   La validation doit d�tecter 6 erreurs (une par contrainte)
-->


<base xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="base-contrainte.xsd">

  <restaurant nom="la tour d'argent" etoile="4" ville="Paris">
    <fermeture>dimanche et lundi</fermeture>
    <menu nom="gourmet" prix="300" />
  </restaurant>

  <ville nom="Paris">
    <plusBeauMonument nom="tour Eiffel" tarif="30" />
    <plusBeauMonument nom="notre dame" tarif="50" />
  </ville>

  <restaurant nom="chez Bocuse" etoile="2" ville="Lyon">
    <fermeture>dimanche</fermeture>
    <menu nom="sp�cialit�s lyonnaises" prix="200" />
    <menu nom="v�g�tarien" prix="299" />
  </restaurant>

  <restaurant nom="MacDo" etoile="0" ville="Marseille">
    <menu nom="standard" prix="35" />
    <menu nom="enfant" prix="20" />
    <menu nom="big" prix="49" />
  </restaurant>

  <ville nom="Lyon" departement="69"></ville>

  <ville nom="Avignon" departement="84">
    <plusBeauMonument nom="le pont" />
  </ville>

</base>
